# Generated by Django 4.2.9 on 2026-01-29 23:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Año")),
                (
                    "month",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Mes",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Monto Presupuestado",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Los meses cerrados no permiten modificaciones",
                        verbose_name="Cerrado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
                "ordering": ["-year", "-month", "cost_center", "category"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("PAPELERIA", "Papelería"),
                            ("LIMPIEZA", "Limpieza"),
                            ("MANTENIMIENTO_MOTOS", "Mantenimiento Motos"),
                            ("MANTENIMIENTO_AUTOMOVILES", "Mantenimiento Automóviles"),
                            ("MANTENIMIENTO_BODEGAS", "Mantenimiento Bodegas"),
                            ("VIATICOS", "Viáticos"),
                            ("SEGURIDAD_HIGIENE", "Seguridad e Higiene"),
                            ("PUBLICIDAD_EVENTOS", "Publicidad y Eventos"),
                            ("CONSUMIBLES", "Consumibles"),
                            ("COMBUSTIBLES", "Combustibles"),
                            ("NOMINA", "Nómina"),
                            ("IMPUESTOS", "Impuestos"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Pieza, Litro, Caja, etc.",
                        max_length=50,
                        verbose_name="Unidad",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Los items inactivos no aparecen en nuevas solicitudes",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="budgets.category",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="BudgetHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto Anterior"
                    ),
                ),
                (
                    "new_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Nuevo Monto"
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Razón del cambio"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="budgets.budget",
                        verbose_name="Presupuesto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Presupuesto",
                "verbose_name_plural": "Historial de Presupuestos",
                "ordering": ["-created_at"],
            },
        ),
    ]
