# Generated by Django 4.2.9 on 2026-01-29 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("budgets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="budgethistory",
            name="changed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificado por",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budgets",
                to="budgets.category",
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="cost_center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budgets",
                to="users.costcenter",
                verbose_name="Centro de Costos",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["category", "is_active"], name="budgets_ite_categor_8a1dff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["year", "month"], name="budgets_bud_year_d841e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["cost_center", "category", "year", "month"],
                name="budgets_bud_cost_ce_371cc2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={("cost_center", "category", "year", "month")},
        ),
    ]
