# Generated by Django 4.2.9 on 2026-01-29 23:54

import autodis_compras.apps.requests.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PurchaseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Número de Solicitud",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripción detallada")),
                (
                    "suggested_supplier",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Proveedor sugerido"
                    ),
                ),
                (
                    "estimated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Monto estimado (MXN)",
                    ),
                ),
                ("required_date", models.DateField(verbose_name="Fecha requerida")),
                ("justification", models.TextField(verbose_name="Justificación")),
                (
                    "budget_excess_justification",
                    models.TextField(
                        blank=True, verbose_name="Justificación de exceso presupuestal"
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[("NORMAL", "Normal"), ("URGENTE", "Urgente")],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="Urgencia",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PENDIENTE_GERENTE", "Pendiente aprobación gerente"),
                            ("APROBADA_POR_GERENTE", "Aprobada por gerente"),
                            ("APROBADA", "Aprobada"),
                            ("EN_PROCESO", "En proceso de compra"),
                            ("COMPRADA", "Comprada"),
                            ("COMPLETADA", "Completada"),
                            ("RECHAZADA_GERENTE", "Rechazada por gerente"),
                            (
                                "RECHAZADA_FINANZAS",
                                "Rechazada por Finanzas/Dir. General",
                            ),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="BORRADOR",
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "manager_approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aprobado por gerente"
                    ),
                ),
                (
                    "final_approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Aprobación final"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Razón de rechazo"),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rechazado"
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de compra"
                    ),
                ),
                (
                    "actual_supplier",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Proveedor real"
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Monto real",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número de factura"
                    ),
                ),
                (
                    "exceeds_budget",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Excede presupuesto"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Compra",
                "verbose_name_plural": "Solicitudes de Compra",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Solo archivos PDF, máximo 10MB",
                        upload_to=autodis_compras.apps.requests.models.request_attachment_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Nombre original"),
                ),
                (
                    "file_size",
                    models.IntegerField(editable=False, verbose_name="Tamaño (bytes)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
            ],
            options={
                "verbose_name": "Archivo Adjunto",
                "verbose_name_plural": "Archivos Adjuntos",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Comentario")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
            ],
            options={
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PENDIENTE_GERENTE", "Pendiente aprobación gerente"),
                            ("APROBADA_POR_GERENTE", "Aprobada por gerente"),
                            ("APROBADA", "Aprobada"),
                            ("EN_PROCESO", "En proceso de compra"),
                            ("COMPRADA", "Comprada"),
                            ("COMPLETADA", "Completada"),
                            ("RECHAZADA_GERENTE", "Rechazada por gerente"),
                            (
                                "RECHAZADA_FINANZAS",
                                "Rechazada por Finanzas/Dir. General",
                            ),
                            ("CANCELADA", "Cancelada"),
                        ],
                        max_length=30,
                        verbose_name="Estado anterior",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PENDIENTE_GERENTE", "Pendiente aprobación gerente"),
                            ("APROBADA_POR_GERENTE", "Aprobada por gerente"),
                            ("APROBADA", "Aprobada"),
                            ("EN_PROCESO", "En proceso de compra"),
                            ("COMPRADA", "Comprada"),
                            ("COMPLETADA", "Completada"),
                            ("RECHAZADA_GERENTE", "Rechazada por gerente"),
                            (
                                "RECHAZADA_FINANZAS",
                                "Rechazada por Finanzas/Dir. General",
                            ),
                            ("CANCELADA", "Cancelada"),
                        ],
                        max_length=30,
                        verbose_name="Nuevo estado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
            ],
            options={
                "verbose_name": "Historial de Estado",
                "verbose_name_plural": "Historial de Estados",
                "ordering": ["created_at"],
            },
        ),
    ]
