# Generated by Django 4.2.9 on 2026-01-29 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("requests", "0001_initial"),
        ("budgets", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="requeststatushistory",
            name="changed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificado por",
            ),
        ),
        migrations.AddField(
            model_name="requeststatushistory",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="requests.purchaserequest",
                verbose_name="Solicitud",
            ),
        ),
        migrations.AddField(
            model_name="requestcomment",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="requests.purchaserequest",
                verbose_name="Solicitud",
            ),
        ),
        migrations.AddField(
            model_name="requestcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="request_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="requestattachment",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="requests.purchaserequest",
                verbose_name="Solicitud",
            ),
        ),
        migrations.AddField(
            model_name="requestattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_attachments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Subido por",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_requests",
                to="budgets.category",
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="cost_center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_requests",
                to="users.costcenter",
                verbose_name="Centro de Costos",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="final_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="final_approvals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aprobador final",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="items",
            field=models.ManyToManyField(
                related_name="purchase_requests",
                to="budgets.item",
                verbose_name="Items",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="manager_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="managed_approvals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Gerente que aprobó",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rejections",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Rechazado por",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Solicitante",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaserequest",
            index=models.Index(
                fields=["status", "created_at"], name="requests_pu_status_8aa348_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaserequest",
            index=models.Index(
                fields=["requester", "status"], name="requests_pu_request_b00888_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaserequest",
            index=models.Index(
                fields=["cost_center", "category", "created_at"],
                name="requests_pu_cost_ce_07c1f9_idx",
            ),
        ),
    ]
