# Generated by Django 4.2.9 on 2026-01-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("SOLICITUD_CREADA", "Solicitud creada"),
                            ("APROBADA_GERENTE", "Aprobada por gerente"),
                            ("APROBADA_FINAL", "Aprobación final"),
                            ("RECHAZADA", "Rechazada"),
                            ("COMENTARIO", "Comentario agregado"),
                            ("FUERA_OFICINA", "Fuera de oficina activado"),
                        ],
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Asunto")),
                ("message", models.TextField(verbose_name="Mensaje")),
                ("sent", models.BooleanField(default=False, verbose_name="Enviado")),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Enviado"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Error")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
            ],
            options={
                "verbose_name": "Notificación por Email",
                "verbose_name_plural": "Notificaciones por Email",
                "ordering": ["-created_at"],
            },
        ),
    ]
