# Generated by Django 4.2.9 on 2026-01-29 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        ("requests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emailnotification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="received_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Destinatario",
            ),
        ),
        migrations.AddField(
            model_name="emailnotification",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="requests.purchaserequest",
                verbose_name="Solicitud",
            ),
        ),
    ]
